server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
