version: '1.0'
services:
  backend:
    image: application
    container_name: application-backend
    ports:
      - "8081:8081"
    links:
      - postgres
    environment:
      DB_URL: postgres
      DB_USERNAME: root
      DB_PASSWORD: password
  postgres:
    image: postgres
    container_name: some-application
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application