version: '1.0'
services:
  postgres:
    image: postgres
    container_name: some-application
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application